# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow_test.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1060, 489)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(630, 10, 401, 441))
        self.groupBox_4.setObjectName("groupBox_4")
        self.progress_view = QtWidgets.QTextEdit(self.groupBox_4)
        self.progress_view.setEnabled(True)
        self.progress_view.setGeometry(QtCore.QRect(10, 20, 381, 401))
        self.progress_view.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.progress_view.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.progress_view.setStyleSheet("font: 12pt \"Adobe Arabic\";\n"
"color: rgb(85, 170, 255);")
        self.progress_view.setUndoRedoEnabled(True)
        self.progress_view.setReadOnly(True)
        self.progress_view.setObjectName("progress_view")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 611, 421))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 591, 201))
        self.groupBox_7.setObjectName("groupBox_7")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_7)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 394, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rb_j3_m_adult = QtWidgets.QRadioButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_j3_m_adult.sizePolicy().hasHeightForWidth())
        self.rb_j3_m_adult.setSizePolicy(sizePolicy)
        self.rb_j3_m_adult.setChecked(True)
        self.rb_j3_m_adult.setObjectName("rb_j3_m_adult")
        self.horizontalLayout.addWidget(self.rb_j3_m_adult)
        self.rb_j3_fm_adult = QtWidgets.QRadioButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_j3_fm_adult.sizePolicy().hasHeightForWidth())
        self.rb_j3_fm_adult.setSizePolicy(sizePolicy)
        self.rb_j3_fm_adult.setObjectName("rb_j3_fm_adult")
        self.horizontalLayout.addWidget(self.rb_j3_fm_adult)
        self.rb_j3_fm = QtWidgets.QRadioButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_j3_fm.sizePolicy().hasHeightForWidth())
        self.rb_j3_fm.setSizePolicy(sizePolicy)
        self.rb_j3_fm.setChecked(False)
        self.rb_j3_fm.setObjectName("rb_j3_fm")
        self.horizontalLayout.addWidget(self.rb_j3_fm)
        self.rb_j3_m = QtWidgets.QRadioButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_j3_m.sizePolicy().hasHeightForWidth())
        self.rb_j3_m.setSizePolicy(sizePolicy)
        self.rb_j3_m.setObjectName("rb_j3_m")
        self.horizontalLayout.addWidget(self.rb_j3_m)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_5.setGeometry(QtCore.QRect(470, 10, 111, 31))
        self.pushButton_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_5.setObjectName("pushButton_5")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_7)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 50, 91, 141))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_6.addWidget(self.label_20)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_7)
        self.layoutWidget2.setGeometry(QtCore.QRect(100, 50, 481, 141))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.le_src_dir = QtWidgets.QLineEdit(self.layoutWidget2)
        self.le_src_dir.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.le_src_dir.setReadOnly(True)
        self.le_src_dir.setObjectName("le_src_dir")
        self.verticalLayout_13.addWidget(self.le_src_dir)
        self.label_src_file_count = QtWidgets.QLabel(self.layoutWidget2)
        self.label_src_file_count.setObjectName("label_src_file_count")
        self.verticalLayout_13.addWidget(self.label_src_file_count)
        self.verticalLayout_15.addLayout(self.verticalLayout_13)
        self.label_src_suggest = QtWidgets.QLabel(self.layoutWidget2)
        self.label_src_suggest.setStyleSheet("color: rgb(85, 170, 255);")
        self.label_src_suggest.setObjectName("label_src_suggest")
        self.verticalLayout_15.addWidget(self.label_src_suggest)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.le_src_align_dir = QtWidgets.QLineEdit(self.layoutWidget2)
        self.le_src_align_dir.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.le_src_align_dir.setReadOnly(True)
        self.le_src_align_dir.setObjectName("le_src_align_dir")
        self.verticalLayout_14.addWidget(self.le_src_align_dir)
        self.label_src_align_file_count = QtWidgets.QLabel(self.layoutWidget2)
        self.label_src_align_file_count.setObjectName("label_src_align_file_count")
        self.verticalLayout_14.addWidget(self.label_src_align_file_count)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        self.label_src_align_suggest = QtWidgets.QLabel(self.layoutWidget2)
        self.label_src_align_suggest.setStyleSheet("color: rgb(85, 170, 255);")
        self.label_src_align_suggest.setObjectName("label_src_align_suggest")
        self.verticalLayout_15.addWidget(self.label_src_align_suggest)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 220, 591, 91))
        self.groupBox_8.setObjectName("groupBox_8")
        self.pb_open_data_dst_dir = QtWidgets.QPushButton(self.groupBox_8)
        self.pb_open_data_dst_dir.setGeometry(QtCore.QRect(480, 19, 101, 31))
        self.pb_open_data_dst_dir.setObjectName("pb_open_data_dst_dir")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_3.setGeometry(QtCore.QRect(480, 50, 101, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_8)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 21, 101, 61))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_9.addWidget(self.label_19)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_8)
        self.layoutWidget4.setGeometry(QtCore.QRect(110, 20, 361, 61))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.le_data_dst_path = QtWidgets.QLineEdit(self.layoutWidget4)
        self.le_data_dst_path.setEnabled(True)
        self.le_data_dst_path.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.le_data_dst_path.setReadOnly(True)
        self.le_data_dst_path.setObjectName("le_data_dst_path")
        self.verticalLayout_10.addWidget(self.le_data_dst_path)
        self.label_dst_suggest = QtWidgets.QLabel(self.layoutWidget4)
        self.label_dst_suggest.setStyleSheet("color: rgb(85, 170, 255);")
        self.label_dst_suggest.setText("")
        self.label_dst_suggest.setObjectName("label_dst_suggest")
        self.verticalLayout_10.addWidget(self.label_dst_suggest)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 320, 591, 61))
        self.groupBox_9.setObjectName("groupBox_9")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_4.setGeometry(QtCore.QRect(480, 20, 101, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_11.addWidget(self.label_18)
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget6.setGeometry(QtCore.QRect(110, 20, 361, 31))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_dst_aligned_suggest = QtWidgets.QLabel(self.layoutWidget6)
        self.label_dst_aligned_suggest.setStyleSheet("color: rgb(85, 170, 255);")
        self.label_dst_aligned_suggest.setText("")
        self.label_dst_aligned_suggest.setObjectName("label_dst_aligned_suggest")
        self.verticalLayout_12.addWidget(self.label_dst_aligned_suggest)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget7 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget7.setGeometry(QtCore.QRect(150, 20, 321, 22))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.rb_use_SAE = QtWidgets.QRadioButton(self.layoutWidget7)
        self.rb_use_SAE.setEnabled(True)
        self.rb_use_SAE.setChecked(True)
        self.rb_use_SAE.setObjectName("rb_use_SAE")
        self.horizontalLayout_8.addWidget(self.rb_use_SAE)
        self.rb_use_Quick96 = QtWidgets.QRadioButton(self.layoutWidget7)
        self.rb_use_Quick96.setEnabled(True)
        self.rb_use_Quick96.setObjectName("rb_use_Quick96")
        self.horizontalLayout_8.addWidget(self.rb_use_Quick96)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 60, 281, 151))
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget8 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 20, 133, 81))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rb_last_model_sae = QtWidgets.QRadioButton(self.layoutWidget8)
        self.rb_last_model_sae.setChecked(True)
        self.rb_last_model_sae.setObjectName("rb_last_model_sae")
        self.verticalLayout.addWidget(self.rb_last_model_sae)
        self.rb_old_model_sae = QtWidgets.QRadioButton(self.layoutWidget8)
        self.rb_old_model_sae.setObjectName("rb_old_model_sae")
        self.verticalLayout.addWidget(self.rb_old_model_sae)
        self.rb_new_model_sae = QtWidgets.QRadioButton(self.layoutWidget8)
        self.rb_new_model_sae.setObjectName("rb_new_model_sae")
        self.verticalLayout.addWidget(self.rb_new_model_sae)
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(150, 110, 51, 17))
        self.label_7.setObjectName("label_7")
        self.layoutWidget9 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget9.setGeometry(QtCore.QRect(150, 40, 111, 31))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.le_old_model_name_sae = QtWidgets.QLineEdit(self.layoutWidget9)
        self.le_old_model_name_sae.setEnabled(False)
        self.le_old_model_name_sae.setInputMask("")
        self.le_old_model_name_sae.setText("")
        self.le_old_model_name_sae.setObjectName("le_old_model_name_sae")
        self.horizontalLayout_9.addWidget(self.le_old_model_name_sae)
        self.layoutWidget10 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget10.setGeometry(QtCore.QRect(150, 70, 111, 31))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.le_new_model_name_sae = QtWidgets.QLineEdit(self.layoutWidget10)
        self.le_new_model_name_sae.setEnabled(False)
        self.le_new_model_name_sae.setInputMask("")
        self.le_new_model_name_sae.setText("")
        self.le_new_model_name_sae.setObjectName("le_new_model_name_sae")
        self.horizontalLayout_10.addWidget(self.le_new_model_name_sae)
        self.layoutWidget11 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget11.setGeometry(QtCore.QRect(200, 100, 61, 38))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget11)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rb_device_GPU_sae = QtWidgets.QRadioButton(self.layoutWidget11)
        self.rb_device_GPU_sae.setEnabled(False)
        self.rb_device_GPU_sae.setChecked(True)
        self.rb_device_GPU_sae.setObjectName("rb_device_GPU_sae")
        self.verticalLayout_3.addWidget(self.rb_device_GPU_sae)
        self.rb_device_CPU_sae = QtWidgets.QRadioButton(self.layoutWidget11)
        self.rb_device_CPU_sae.setEnabled(False)
        self.rb_device_CPU_sae.setChecked(False)
        self.rb_device_CPU_sae.setObjectName("rb_device_CPU_sae")
        self.verticalLayout_3.addWidget(self.rb_device_CPU_sae)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(300, 60, 291, 151))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_11.setGeometry(QtCore.QRect(160, 110, 51, 16))
        self.label_11.setObjectName("label_11")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_6)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 141, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rb_last_model_quick96 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rb_last_model_quick96.setEnabled(False)
        self.rb_last_model_quick96.setChecked(True)
        self.rb_last_model_quick96.setObjectName("rb_last_model_quick96")
        self.verticalLayout_2.addWidget(self.rb_last_model_quick96)
        self.rb_old_model_quick96 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rb_old_model_quick96.setEnabled(False)
        self.rb_old_model_quick96.setObjectName("rb_old_model_quick96")
        self.verticalLayout_2.addWidget(self.rb_old_model_quick96)
        self.rb_new_model_quick96 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rb_new_model_quick96.setEnabled(False)
        self.rb_new_model_quick96.setObjectName("rb_new_model_quick96")
        self.verticalLayout_2.addWidget(self.rb_new_model_quick96)
        self.layoutWidget12 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget12.setGeometry(QtCore.QRect(160, 70, 121, 31))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget12)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.le_new_model_name_quick96 = QtWidgets.QLineEdit(self.layoutWidget12)
        self.le_new_model_name_quick96.setEnabled(False)
        self.le_new_model_name_quick96.setObjectName("le_new_model_name_quick96")
        self.horizontalLayout_11.addWidget(self.le_new_model_name_quick96)
        self.layoutWidget13 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget13.setGeometry(QtCore.QRect(160, 40, 121, 31))
        self.layoutWidget13.setObjectName("layoutWidget13")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget13)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget13)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        self.le_old_model_name_quick96 = QtWidgets.QLineEdit(self.layoutWidget13)
        self.le_old_model_name_quick96.setEnabled(False)
        self.le_old_model_name_quick96.setObjectName("le_old_model_name_quick96")
        self.horizontalLayout_12.addWidget(self.le_old_model_name_quick96)
        self.layoutWidget14 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget14.setGeometry(QtCore.QRect(210, 100, 71, 38))
        self.layoutWidget14.setObjectName("layoutWidget14")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget14)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.rb_device_GPU_quick96 = QtWidgets.QRadioButton(self.layoutWidget14)
        self.rb_device_GPU_quick96.setEnabled(False)
        self.rb_device_GPU_quick96.setChecked(True)
        self.rb_device_GPU_quick96.setObjectName("rb_device_GPU_quick96")
        self.verticalLayout_4.addWidget(self.rb_device_GPU_quick96)
        self.rb_device_CPU_quick96 = QtWidgets.QRadioButton(self.layoutWidget14)
        self.rb_device_CPU_quick96.setEnabled(False)
        self.rb_device_CPU_quick96.setObjectName("rb_device_CPU_quick96")
        self.verticalLayout_4.addWidget(self.rb_device_CPU_quick96)
        self.layoutWidget15 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget15.setGeometry(QtCore.QRect(90, 220, 391, 31))
        self.layoutWidget15.setObjectName("layoutWidget15")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget15)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget15)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.pb_save = QtWidgets.QPushButton(self.layoutWidget15)
        self.pb_save.setEnabled(False)
        self.pb_save.setObjectName("pb_save")
        self.horizontalLayout_7.addWidget(self.pb_save)
        self.pb_end = QtWidgets.QPushButton(self.layoutWidget15)
        self.pb_end.setEnabled(False)
        self.pb_end.setObjectName("pb_end")
        self.horizontalLayout_7.addWidget(self.pb_end)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.label_12.setObjectName("label_12")
        self.le_model_path = QtWidgets.QLineEdit(self.tab_3)
        self.le_model_path.setEnabled(True)
        self.le_model_path.setGeometry(QtCore.QRect(110, 20, 391, 21))
        self.le_model_path.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.le_model_path.setReadOnly(True)
        self.le_model_path.setObjectName("le_model_path")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_6.setGeometry(QtCore.QRect(510, 20, 81, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        self.layoutWidget16 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget16.setGeometry(QtCore.QRect(10, 60, 101, 131))
        self.layoutWidget16.setObjectName("layoutWidget16")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget16)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget16)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_7.addWidget(self.label_15)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget16)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_7.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget16)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_7.addWidget(self.label_23)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget16)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_7.addWidget(self.label_16)
        self.layoutWidget17 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget17.setGeometry(QtCore.QRect(110, 60, 391, 131))
        self.layoutWidget17.setObjectName("layoutWidget17")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget17)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.le_dst_merge_dir = QtWidgets.QLineEdit(self.layoutWidget17)
        self.le_dst_merge_dir.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.le_dst_merge_dir.setReadOnly(True)
        self.le_dst_merge_dir.setObjectName("le_dst_merge_dir")
        self.verticalLayout_8.addWidget(self.le_dst_merge_dir)
        self.label_dst_merge_file_count = QtWidgets.QLabel(self.layoutWidget17)
        self.label_dst_merge_file_count.setText("")
        self.label_dst_merge_file_count.setObjectName("label_dst_merge_file_count")
        self.verticalLayout_8.addWidget(self.label_dst_merge_file_count)
        self.label_dst_merge_suggest = QtWidgets.QLabel(self.layoutWidget17)
        self.label_dst_merge_suggest.setStyleSheet("color: rgb(85, 170, 255);")
        self.label_dst_merge_suggest.setText("")
        self.label_dst_merge_suggest.setObjectName("label_dst_merge_suggest")
        self.verticalLayout_8.addWidget(self.label_dst_merge_suggest)
        self.le_result_dir = QtWidgets.QLineEdit(self.layoutWidget17)
        self.le_result_dir.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.le_result_dir.setReadOnly(True)
        self.le_result_dir.setObjectName("le_result_dir")
        self.verticalLayout_8.addWidget(self.le_result_dir)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_7.setGeometry(QtCore.QRect(510, 100, 79, 20))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 140, 79, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1060, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(MainWindow.StartTrain)
        self.rb_last_model_sae.toggled['bool'].connect(MainWindow.modelSelect)
        self.rb_new_model_sae.toggled['bool'].connect(MainWindow.modelSelect)
        self.rb_old_model_sae.toggled['bool'].connect(MainWindow.modelSelect)
        self.le_new_model_name_sae.editingFinished.connect(MainWindow.modelNameEdit)
        self.le_old_model_name_sae.editingFinished.connect(MainWindow.modelNameEdit)
        self.rb_use_SAE.toggled['bool'].connect(MainWindow.AlgoSelect)
        self.rb_use_Quick96.toggled['bool'].connect(MainWindow.AlgoSelect)
        self.rb_device_CPU_sae.toggled['bool'].connect(MainWindow.DeviceSelect)
        self.rb_device_GPU_sae.toggled['bool'].connect(MainWindow.DeviceSelect)
        self.pb_save.clicked.connect(MainWindow.SaveOnce)
        self.pb_end.clicked.connect(MainWindow.StopTrain)
        self.pb_open_data_dst_dir.clicked.connect(MainWindow.ChooseDstDir)
        self.le_data_dst_path.editingFinished.connect(MainWindow.EditDstDir)
        self.pushButton_3.clicked.connect(MainWindow.extract_dst_video)
        self.pushButton_4.clicked.connect(MainWindow.extract_full_face)
        self.pushButton_7.clicked.connect(MainWindow.merge_result)
        self.pushButton_2.clicked.connect(MainWindow.merge_video)
        self.rb_last_model_quick96.clicked.connect(MainWindow.modelSelect)
        self.rb_old_model_quick96.clicked.connect(MainWindow.modelSelect)
        self.rb_new_model_quick96.clicked.connect(MainWindow.modelSelect)
        self.rb_device_CPU_quick96.clicked.connect(MainWindow.DeviceSelect)
        self.rb_device_GPU_quick96.clicked.connect(MainWindow.DeviceSelect)
        self.le_old_model_name_quick96.editingFinished.connect(MainWindow.modelNameEdit)
        self.le_new_model_name_quick96.editingFinished.connect(MainWindow.modelNameEdit)
        self.pushButton_5.clicked.connect(MainWindow.extract_j3_face)
        self.rb_j3_m_adult.clicked.connect(MainWindow.update_src)
        self.rb_j3_fm_adult.clicked.connect(MainWindow.update_src)
        self.rb_j3_fm.clicked.connect(MainWindow.update_src)
        self.rb_j3_m.clicked.connect(MainWindow.update_src)
        self.pushButton_6.clicked.connect(MainWindow.ChooseModelDir)
        self.le_src_dir.customContextMenuRequested['QPoint'].connect(MainWindow.go_to_src)
        self.le_src_align_dir.customContextMenuRequested['QPoint'].connect(MainWindow.go_to_src_align)
        self.le_dst_merge_dir.customContextMenuRequested['QPoint'].connect(MainWindow.go_to_dst_merge)
        self.le_result_dir.customContextMenuRequested['QPoint'].connect(MainWindow.go_to_result)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "剑三订制换脸工具V1.0"))
        self.groupBox_4.setTitle(_translate("MainWindow", "操作进度"))
        self.groupBox_7.setTitle(_translate("MainWindow", "第一步,选择要替换的剑三标准脸"))
        self.rb_j3_m_adult.setText(_translate("MainWindow", "成男标准脸"))
        self.rb_j3_fm_adult.setText(_translate("MainWindow", "成女标准脸"))
        self.rb_j3_fm.setText(_translate("MainWindow", "萝莉标准脸"))
        self.rb_j3_m.setText(_translate("MainWindow", "正太标准脸"))
        self.pushButton_5.setText(_translate("MainWindow", "开始提取人脸"))
        self.label.setText(_translate("MainWindow", "目标文件夹"))
        self.label_4.setText(_translate("MainWindow", "操作建议"))
        self.label_20.setText(_translate("MainWindow", "目标人脸目录"))
        self.label_3.setText(_translate("MainWindow", "操作建议"))
        self.label_src_file_count.setText(_translate("MainWindow", "TextLabel"))
        self.label_src_suggest.setText(_translate("MainWindow", "TextLabel"))
        self.label_src_align_file_count.setText(_translate("MainWindow", "TextLabel"))
        self.label_src_align_suggest.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_8.setTitle(_translate("MainWindow", "第二步.提取目标视频帧"))
        self.pb_open_data_dst_dir.setText(_translate("MainWindow", "选择视频"))
        self.pushButton_3.setText(_translate("MainWindow", "开始提取图像"))
        self.label_2.setText(_translate("MainWindow", "目标视频文件地址"))
        self.label_19.setText(_translate("MainWindow", "操作建议"))
        self.groupBox_9.setTitle(_translate("MainWindow", "第三步.从目标视频帧中提取人脸"))
        self.pushButton_4.setText(_translate("MainWindow", "开始提取人脸"))
        self.label_18.setText(_translate("MainWindow", "操作建议"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "数据准备"))
        self.label_6.setText(_translate("MainWindow", "算法精度"))
        self.rb_use_SAE.setText(_translate("MainWindow", "高配算法"))
        self.rb_use_Quick96.setText(_translate("MainWindow", "低配算法"))
        self.groupBox_5.setTitle(_translate("MainWindow", "高配算法"))
        self.rb_last_model_sae.setText(_translate("MainWindow", "继续上一次的训练配置"))
        self.rb_old_model_sae.setText(_translate("MainWindow", "使用一个之前的模型"))
        self.rb_new_model_sae.setText(_translate("MainWindow", "新建一个训练模型"))
        self.label_7.setText(_translate("MainWindow", "设备选择"))
        self.label_9.setText(_translate("MainWindow", "旧模型名"))
        self.label_8.setText(_translate("MainWindow", "新模型名"))
        self.rb_device_GPU_sae.setText(_translate("MainWindow", "GPU"))
        self.rb_device_CPU_sae.setText(_translate("MainWindow", "CPU"))
        self.groupBox_6.setTitle(_translate("MainWindow", "低配算法"))
        self.label_11.setText(_translate("MainWindow", "设备选择"))
        self.rb_last_model_quick96.setText(_translate("MainWindow", "继续上一次的训练配置"))
        self.rb_old_model_quick96.setText(_translate("MainWindow", "使用一个之前的模型"))
        self.rb_new_model_quick96.setText(_translate("MainWindow", "新建一个训练模型"))
        self.label_10.setText(_translate("MainWindow", "新模型名"))
        self.label_5.setText(_translate("MainWindow", "旧模型名"))
        self.rb_device_GPU_quick96.setText(_translate("MainWindow", "GPU"))
        self.rb_device_CPU_quick96.setText(_translate("MainWindow", "CPU"))
        self.pushButton.setText(_translate("MainWindow", "开始训练"))
        self.pb_save.setText(_translate("MainWindow", "保存结果"))
        self.pb_end.setText(_translate("MainWindow", "结束训练"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "训练模型"))
        self.label_12.setText(_translate("MainWindow", "模型路径"))
        self.pushButton_6.setText(_translate("MainWindow", "选择模型"))
        self.label_15.setText(_translate("MainWindow", "目标人脸合成目录："))
        self.label_22.setText(_translate("MainWindow", "文件数量统计"))
        self.label_23.setText(_translate("MainWindow", "操作建议"))
        self.label_16.setText(_translate("MainWindow", "合成视频输出目录："))
        self.pushButton_7.setToolTip(_translate("MainWindow", "使用当前已经训练好的模型，把剑三虚拟角色的脸部特征替换到目标图片的人脸上"))
        self.pushButton_7.setText(_translate("MainWindow", "1.逐帧合成"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "将最终生成的替换后的图片合成为视频文件"))
        self.pushButton_2.setText(_translate("MainWindow", "2.合成视频"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "视频合成"))
